name: Workflow for API Backend coding task

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: php:8-fpm-alpine3.15
    strategy:
      matrix:
        php: [8.1]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lotr_test
        ports:
          - 3306/tcp
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change directory to app/
        run: cd app/

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, zip, pcntl

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest

      - name: Run PHPUnit
        run: vendor/bin/phpunit
